### ISSUE TITLE
The 'pci_mig_accelerator_0' IP is locked in vivado 2021.1

### ISSUE THREAD

**Issue by Dund1Tang** [gnodipac886/ViT-FPGA-TPU#1]
The 'pci_mig_accelerator_0' IP is locked due to 'IP definition not found'

The project file that reported the error is 'pci_mig_16_v2' in the folder 'v2.0/hw/tpu_16'

Is the 'pci_mig_accelerator_0' related file missing from the 'ip_repo' folder, or other possible reason for this problem?

Thanks,

**Comment by gnodipac886** [comment]
Hmmm could you try this IP, I think it should this one... the naming is off

[pci_mig_pci_mig_accelerator_0_0](https://github.com/gnodipac886/ViT-FPGA-TPU/tree/main/v2.0/hw/tpu_16/ip_repo/pci_mig_pci_mig_accelerator_0_0)

**Comment by Dund1Tang** [comment]
Thanks for your reply!
Is it possible that this is because some code is not being provided?
I noticed that the 'IP Catalog' in the 'pci_mig_16_v2' project only
contains the IP [fp_systolic_array].
And the 'tmp_edit_project' project in the folder
'tpu_16/ip_repo/fp_sys_array' also has an invalid path in 'IP Repositories'.

**Comment by Dund1Tang** [comment]
![Uploading the 'IP Catalog' in the 'pci_mig_16_v2' project only contains the IP [fp_systolic_array].png…]()

**Comment by gnodipac886** [comment]
I think all the code is provided. Can you try reconstructing the project from the [block diagram](https://github.com/gnodipac886/ViT-FPGA-TPU/blob/main/images/v2_bd.png)?
Currently I don't have access to a machine that can run vivado so I can only support you with this manner.

**Comment by gnodipac886** [comment]
closing this for now... please reopen it if you are still having issues with this
